/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import com.sun.org.apache.bcel.internal.Constants;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;//koding untuk mengimport swing tabel

/**
 *
 * @author S855
 */
public class login extends javax.swing.JFrame {

   // koneksi tk = new koneksi();

    /**
     * Creates new form login
     */
    public login() {
        initComponents();

    }
 public void ListenerMulai(ActionListener act){
        login.addActionListener(act);
    }
    
    public String getID(){
       String data= user.getText();
       return data;
    }
    
    public String getpas(){
       String data= pas.getText();
       return data;
    }
    public void setMessage(String X) {
        pesan.setText(X);
    }
    
    public void setHasil(String X) {
         JOptionPane.showMessageDialog(rootPane, X);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JButton();
        user = new javax.swing.JTextField();
        pas = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pesan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/tlogin.png"))); // NOI18N
        login.setBorder(null);
        login.setBorderPainted(false);
        login.setContentAreaFilled(false);
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 170, 40));

        user.setBackground(new java.awt.Color(255, 93, 122));
        user.setFont(new java.awt.Font("Swis721 Blk BT", 0, 24)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 580, 50));

        pas.setBackground(new java.awt.Color(255, 93, 122));
        pas.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 24)); // NOI18N
        pas.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(pas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 580, 50));

        jLabel2.setFont(new java.awt.Font("Swis721 Hv BT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 255));
        jLabel2.setText("ID_User");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Swis721 Hv BT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 255));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));
        getContentPane().add(pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 180, 290, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/backPBO.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField pas;
    private javax.swing.JLabel pesan;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
