/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author S855
 */
public class Persediaan extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Persediaan() {
        
          initComponents();//koding untuk menampilkan komponen-komponen dari JFrame
    }
    
     public void setTabel(DefaultTableModel m){
          
         tabel.setModel(m);
    }
        public void ListenerTabel( MouseListener act){
        tabel.addMouseListener(act );
    }
        public void ListenerBack(ActionListener act){
        back.addActionListener(act);
    }
           public void ListenerCreate(ActionListener act){
        create.addActionListener(act);
    }
     
    public void ListenerEdit(ActionListener act){
        edit.addActionListener(act);
    }
     
  
     public void ListenerRefresh(ActionListener act){
        refresh.addActionListener(act);
    }
     
      public String getID(){
       String data= ID.getText();
       return data;
    }
       public String getKK(){
       String data=String.valueOf( kategori.getSelectedItem());
       return data;
    }
      public String geNama(){
       String data= nama.getText();
       return data;
    }
      public String getHBeli(){
       String data= hBeli.getText();
       return data;
    }
    
      public String getHJual(){
       String data=  hJual.getText();
       return data;
    }
      
      public String getQty(){
       String data = qty.getText();
       return data;
    }
       public void setPesan(String X) {
         JOptionPane.showMessageDialog(rootPane, X);

    }
       public void setKategori(String nama){
           kategori.addItem( nama);
       }
//      public DoublegetQty(){
//       Double data= Double.parseDouble( qty.getText());
//       return data;
//    }
          public Object getTableValue(int a, int b) {
        Object value = tabel.getValueAt(a, b);
        return value;
 }

           public void disbanCreate(){
      create.setEnabled(false);
  }
   public void disbanEdit(){
      edit.setEnabled(false);
  }
     public void enableEdit(){
      edit.setEnabled(true);
  }
  public void disbanID(){
      ID.disable();
  }
  public Object getTableValue( int b) {
        Object value = tabel.getValueAt(getRowTable(), b);
        return value;
 }
  public int getRowTable() {
        int row = tabel.getSelectedRow();// koding untuk menyimpan  angka baris yang diseleksi
        return row;
    }
  
  public int getColTable() {
        int row = tabel.getSelectedColumn();// koding untuk menyimpan  angka baris yang diseleksi
        return row;
    }
  public void setID( String nim){
       ID.setText(nim);
    }
          public void setNamaB(String nm){
       nama.setText(nm);
    }
            public void setJumlah(String nm){
       qty.setText(nm);
    }
              public void setHargB(String nm){
       hBeli.setText(nm);
    }
              
              public void setHargJ(String nm){
       hJual.setText(nm);
    }
            
              public void seKatego(String nm){
       kategori.addItem(nm);
    }  
//       public int getdata(){
//       int data=Integer.parseInt( borang.getText());
//       return data;
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        qty = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        hBeli = new javax.swing.JTextField();
        edit = new javax.swing.JButton();
        kategori = new javax.swing.JComboBox();
        create = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        hJual = new javax.swing.JTextField();
        refresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(811, 598));
        setPreferredSize(new java.awt.Dimension(811, 598));
        getContentPane().setLayout(null);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product", "Kategori", "Quantitas", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 220, 660, 110);

        back.setText("BACK");
        getContentPane().add(back);
        back.setBounds(80, 520, 100, 40);

        jLabel2.setText("Nama Barang");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 420, 80, 20);

        jLabel3.setText("ID Barang");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 350, 80, 20);

        jLabel4.setText("Kuantitas");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 450, 70, 20);

        jLabel5.setText("Harga Beli");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(430, 350, 80, 20);
        getContentPane().add(ID);
        ID.setBounds(170, 350, 140, 20);
        getContentPane().add(nama);
        nama.setBounds(170, 420, 140, 20);
        getContentPane().add(qty);
        qty.setBounds(170, 450, 140, 20);

        jLabel6.setText("Kategori");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 380, 70, 20);
        getContentPane().add(hBeli);
        hBeli.setBounds(520, 350, 150, 20);

        edit.setText("Update");
        getContentPane().add(edit);
        edit.setBounds(580, 410, 100, 40);

        getContentPane().add(kategori);
        kategori.setBounds(170, 380, 140, 20);

        create.setText("Create");
        getContentPane().add(create);
        create.setBounds(370, 460, 100, 40);

        jLabel7.setText("Harga Jual");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(420, 380, 80, 20);
        getContentPane().add(hJual);
        hJual.setBounds(520, 380, 150, 20);

        refresh.setText("Refresh");
        getContentPane().add(refresh);
        refresh.setBounds(370, 410, 100, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/backPBO.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 598);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Persediaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Persediaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Persediaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Persediaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Persediaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JButton back;
    private javax.swing.JButton create;
    private javax.swing.JButton edit;
    private javax.swing.JTextField hBeli;
    private javax.swing.JTextField hJual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox kategori;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField qty;
    private javax.swing.JButton refresh;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
