/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.text.SimpleDateFormat;
//import javax.swing.table.DefaultTableModel;
import java.util.Date;
import javax.swing.JOptionPane;
import com.sun.org.apache.bcel.internal.Constants;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;//koding untuk mengimport swing tabel
/**
 *
 * @author S855
 */
public class transaksi extends javax.swing.JFrame  {
//koneksi tk=new koneksi();
    /**
     * Creates new form login
     */
    public transaksi() {
        initComponents();
        datenow();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        tobay = new javax.swing.JLabel();
        create = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bali = new javax.swing.JLabel();
        KK = new javax.swing.JComboBox();
        NB = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        Ltanggal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kuantitas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        diskon = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        refresh = new javax.swing.JButton();
        bayar = new javax.swing.JButton();
        uang = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No_Akun", "Nama Akun", "jumlah", "Harga satuan", "Total"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(450, 270, 870, 320);

        tobay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tobay.setText("Total");
        getContentPane().add(tobay);
        tobay.setBounds(1030, 610, 220, 40);

        create.setText("Stok");
        getContentPane().add(create);
        create.setBounds(30, 203, 80, 40);

        edit.setText("Input");
        getContentPane().add(edit);
        edit.setBounds(140, 203, 70, 40);

        back.setText("Back");
        getContentPane().add(back);
        back.setBounds(1140, 180, 80, 40);

        jLabel3.setText("Bayar");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(740, 600, 160, 50);

        bali.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bali.setText("Kembalian");
        getContentPane().add(bali);
        bali.setBounds(740, 660, 150, 40);

        getContentPane().add(KK);
        KK.setBounds(190, 290, 110, 30);

        getContentPane().add(NB);
        NB.setBounds(190, 340, 170, 30);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        Ltanggal.setBackground(new java.awt.Color(204, 204, 204));
        Ltanggal.setFont(new java.awt.Font("Swis721 Blk BT", 0, 36)); // NOI18N
        Ltanggal.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(Ltanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ltanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(400, 40, 640, 100);

        jLabel5.setFont(new java.awt.Font("Stencil Std", 0, 130)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 153));
        jLabel5.setText("C");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 10, 110, 100);
        getContentPane().add(kuantitas);
        kuantitas.setBounds(190, 390, 150, 30);

        jLabel6.setFont(new java.awt.Font("Trajan Pro", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 204));
        jLabel6.setText("Jumlah");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(371, 170, 99, 30);

        jLabel7.setText("Kategori");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 294, 70, 20);

        jLabel8.setText("Nama Barang");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 344, 80, 30);

        jLabel9.setText("Kuantitas");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 394, 70, 20);
        getContentPane().add(diskon);
        diskon.setBounds(190, 440, 150, 30);

        jLabel10.setText("Diskon");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(80, 444, 60, 20);

        refresh.setText("Refresh");
        getContentPane().add(refresh);
        refresh.setBounds(370, 203, 90, 30);

        bayar.setText("Bayar");
        getContentPane().add(bayar);
        bayar.setBounds(563, 603, 100, 50);
        getContentPane().add(uang);
        uang.setBounds(840, 600, 120, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/BackTrans.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1367, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void datenow(){
        Date tanggal = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        System.out.println(sdf.format(tanggal));
       
        
      Ltanggal.setText("Tanggal : "+sdf.format(tanggal));
    }
    public String getTGL(){
        Date tanggal = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-mm-dd");
        String datee=sdf.toString();
         System.out.println(datee);
       
        return datee;
    }
      public void setTabel(DefaultTableModel m){
          
         tabel.setModel(m);
    }
//        public void ListenerTabel( MouseListener act){
//        tabel.addMouseListener(act );
//    }
        public void ListenerBack(ActionListener act){
        back.addActionListener(act);
    }
           public void ListenerBayar(ActionListener act){
        bayar.addActionListener(act);
    }
           public void ListenerCreate(ActionListener act){
        create.addActionListener(act);
    }
     
    public void ListenerEdit(ActionListener act){
        edit.addActionListener(act);
    }
     
//    public void tambahrow(DefaultTableModel m){
////        tabel.editCellAt(int baris, int kolom)
//   tabel.add(m, rootPane);
//    }
   public void ListenerKK(ActionListener act){
        KK.addActionListener(act);
    }
     public void ListenerRefresh(ActionListener act){
        refresh.addActionListener(act);
    }
   
     public Object getTableValue( int b) {
        Object value = tabel.getValueAt(getRowTable(), b);
        return value;
 }
  public int getRowTable() {
        int row = tabel.getSelectedRow();// koding untuk menyimpan  angka baris yang diseleksi
        return row;
    }
  
  public int getColTable() {
        int row = tabel.getSelectedColumn();// koding untuk menyimpan  angka baris yang diseleksi
        return row;
    }
    public void setKategori(String nama){
           KK.addItem( nama);
       }
    public String getKK(){
        String kk=(String)KK.getSelectedItem();
    String kk2=konvertKK(kk);
        return kk2;
    }
    public  String konvertKK(String k){
    String KK=k;
    String hasil;
    if(KK.equals("Makanan Berat")){
        hasil="MB";
    }
   else if(KK.equals("Makanan Ringan")){
        hasil="MK";
    }
    
   else if(KK.equals("Minuman")){
        hasil="MM";
    }
    else{hasil="OT";}
  System.out.println(KK+"=="+hasil);
    
    return hasil;

}
   
    public void setNamaB(String nama){
           NB.addItem(nama);
       }
    public String getnamaB(){
        String kk=(String)NB.getSelectedItem();
        return kk;
    }
        public void hapusNB(){
        NB.removeAllItems();
    }
    public String getUang(){
        return uang.getText();
    }
    public String getQty(){
        return kuantitas.getText();
    }
    public String getDisc(){
        return diskon.getText();
    }
     public void setPesan(String X) {
         JOptionPane.showMessageDialog(rootPane, X);

    }
     public void disbanCreate(){
         create.enable(false);
     }
     public void setTobay(String X){
         tobay.setText("Total ="+X);
     }
     public void setBali(String X){
         bali.setText("kembali ="+X);
     }
        /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox KK;
    private javax.swing.JLabel Ltanggal;
    private javax.swing.JComboBox NB;
    private javax.swing.JButton back;
    private javax.swing.JLabel bali;
    private javax.swing.JButton bayar;
    private javax.swing.JButton create;
    private javax.swing.JTextField diskon;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kuantitas;
    private javax.swing.JButton refresh;
    private javax.swing.JTable tabel;
    private javax.swing.JLabel tobay;
    private javax.swing.JTextField uang;
    // End of variables declaration//GEN-END:variables
}
