/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author S855
 */
public class utama extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public utama() {
        
        initComponents();
    }
    
    public void ListenerTrans(ActionListener act){
        trans.addActionListener(act);
    }
     
    public void ListenerTrLain(ActionListener act){
        tralain.addActionListener(act);
    }
     
    public void ListenerAdmin(ActionListener act){
        buatAdmin.addActionListener(act);
    }
 
   
     
    public void ListenerJurnal(ActionListener act){
        jurnal.addActionListener(act);
    }
     
    public void ListenerKartuP(ActionListener act){
        kartuP.addActionListener(act);
    }
     
//    public void ListenerLap(ActionListener act){
//        lapKeu.addActionListener(act);
//    }
     
    public void ListenerLogout(ActionListener act){
        logout.addActionListener(act);
    }
     
    public void ListenerBB(ActionListener act){
        BB.addActionListener(act);
    }
     public void setHasil(String X) {
         JOptionPane.showMessageDialog(rootPane, X);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        trans = new javax.swing.JButton();
        jurnal = new javax.swing.JButton();
        BB = new javax.swing.JButton();
        buatAdmin = new javax.swing.JButton();
        kartuP = new javax.swing.JButton();
        tralain = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 607));
        getContentPane().setLayout(null);

        trans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/ttrans.png"))); // NOI18N
        trans.setBorder(null);
        trans.setBorderPainted(false);
        trans.setContentAreaFilled(false);
        getContentPane().add(trans);
        trans.setBounds(80, 240, 300, 40);

        jurnal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/tjurnal.png"))); // NOI18N
        getContentPane().add(jurnal);
        jurnal.setBounds(80, 330, 300, 40);

        BB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/tBB.png"))); // NOI18N
        getContentPane().add(BB);
        BB.setBounds(80, 430, 300, 40);

        buatAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/tadm.png"))); // NOI18N
        getContentPane().add(buatAdmin);
        buatAdmin.setBounds(410, 240, 300, 40);

        kartuP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/tkartu.png"))); // NOI18N
        getContentPane().add(kartuP);
        kartuP.setBounds(410, 330, 300, 40);

        tralain.setBackground(new java.awt.Color(153, 153, 255));
        tralain.setFont(new java.awt.Font("Trajan Pro", 0, 24)); // NOI18N
        tralain.setForeground(new java.awt.Color(153, 51, 0));
        tralain.setText("Transaksi Lainnya");
        getContentPane().add(tralain);
        tralain.setBounds(410, 430, 300, 40);

        logout.setText("LOGOUT");
        getContentPane().add(logout);
        logout.setBounds(590, 520, 100, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG/backPBO.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
        //</editor-fold>
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BB;
    private javax.swing.JButton buatAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jurnal;
    private javax.swing.JButton kartuP;
    private javax.swing.JButton logout;
    private javax.swing.JButton tralain;
    private javax.swing.JButton trans;
    // End of variables declaration//GEN-END:variables
}
